notifications:
  email: false

language: node_js
node_js:
  - 12

matrix:
  include:
      env: TO_TEST=FRONTEND
      env: TO_TEST=BACKEND

cache: npm

services: mongodb

git:
  quiet: true

# branches:
#   only:
#     - master

install:
  - if [ "$TO_TEST" = "FRONTEND" ]; then cd $TRAVIS_BUILD_DIR && cd client && npm i; fi
  - if [ "$TO_TEST" = "BACKEND" ]; then cd $TRAVIS_BUILD_DIR  && cd server && npm i; fi


script:
  - if [ "$TO_TEST" = "FRONTEND" ]; then cd $TRAVIS_BUILD_DIR  && cd client && npm run test; fi
  - if [ "$TO_TEST" = "BACKEND" ]; then cd $TRAVIS_BUILD_DIR  && cd server && npm run test; fi
